version: '3'

services:
  frontend:
    image: frontend
    build: ./client
    container_name: react-ui
    ports:
      - "5173:3000"
    stdin_open: true
    tty: true   
    depends_on:
      - backend
    networks:
      - mern-network
    
  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: node-api
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on:
      - database
    networks:
      - mern-network
  # backend:
  #   image: backend
  #   build: ./api
  #   container_name: node-api
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - database
    
  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - /home/faith/mongo-backup:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  db-data:
